Enable Django caching with Redis.
cloudigrade/cloudigrade pull request #1240
Opened 2022-06-16 12:57 UTC by abellotti

Enable Django caching with Redis.
- include the django-redis package.
- enable the caching against redis using the configured redis host and auth.
- added internal /internal/cache endpoint to getting and setting key values.

2022-06-16 13:08 UTC, abellotti commented
Adding Django redis caching.

- With a shared Redis, all cache keys are prefixed with "{CLOUDIGRADE_ENVIRONMENT}-cloudigrade"
- Default caching TTL is honored via settings.CACHE_TTL_DEFAULT (60 seconds)
- Internal API exposed for setting and querying cache keys.


```
$ http post localhost:8000/internal/testkey/ value="test value" timeout=120

POST /internal/cache/testkey/
{
    value: "test value",
    timeout: "120",
}
```

```
$ http localhost:8000/internal/testkey/

GET /internal/cache/testkey/
```

2022-06-17 20:31 UTC, abellotti commented
/retest

2022-06-21 15:04 UTC, infinitewarp requested changes
Looking good. 👍  I suspect the answer to my one question here will be "no…", and if that's the case, I'll just approve what we have now.

2022-06-21 15:04 UTC, infinitewarp commented on cloudigrade/internal/views.py
> +            return Response(content_type="text/plain", data=value)
One maybe not so minor request: How would you feel about including the key's TTL in the response as an HTTP response header, or is it even possible? Ideally something like…

```
ttl = which function call?
headers = {"X-CLOUDIGRADE-CACHE-TTL": ttl}
...
return Response(content_type="text/plain", headers=headers, data=value)
```

I looked briefly through the standard Django docs for the cache framework, and I didn't find any functions that return the TTL/expiration time. This is a little surprising, but I guess maybe it doesn't exist if all backends don't support explicit timing.

I did find these suggestion in [this stack overflow question](https://stackoverflow.com/questions/18203116/can-i-get-expiration-time-of-specified-key-in-django-cache), though:
```
# to get the unix timestamp
cache._expire_info.get('foo') 
```
or for Redis specifically:
```
cache.ttl('foo:bar:2020-09-01')
```
Though, the latter probably wouldn't work with our unit tests sine we use locmem.

All of this makes me think that what I'm asking for either isn't possible at all or probably isn't possible using supported/stable APIs. 😕 

Thoughts?

2022-06-21 17:02 UTC, abellotti commented on cloudigrade/internal/views.py
> +            return Response(content_type="text/plain", data=value)
it is definitely possible to get the ttl in either case as per the get_key_expiration() example in that   stack overflow. So if you think we need it, let's return that too. The only thing I'd recommend differently is the response, instead of the data in body and ttl in header (2 places to look at), what about returning a json, i.e. similar to the post data above https://github.com/cloudigrade/cloudigrade/pull/1240#issuecomment-1157640881 for consistency, we can return the equivalent in json. so you'd get the data via response.data["value"].

```
$ http localhost:8000/internal/testkey/

GET /internal/cache/testkey/
{
    value: "test value",
    timeout: "120",
}
```

thoughts ?

2022-06-22 00:58 UTC, abellotti commented on cloudigrade/internal/views.py
> +            return Response(content_type="text/plain", data=value)
@infinitewarp ☝️ is not too bad: https://github.com/abellotti/cloudigrade/compare/435727a56a7f45dc2d701389161264f25d16fa24...cb8565d4f64f59f025004e0293780b3bcc8ec1d6

Let me know

2022-06-24 10:40 UTC, infinitewarp commented on cloudigrade/internal/views.py
> +            return Response(content_type="text/plain", data=value)
Sorry for the delay! Yes, your sample output looks like a good solution to me. 🙂 

Your new `get_cache_key_timeout` is a little more complex than I anticipated, but it's only as complex as necessary now that I see all the moving parts. I'm okay with this!

I would imagine it's very unlikely that we will change to a different cache backend any time soon, and if we do, we'll need to update that function since new backend-specific failures likely won't be caught by unit tests. Maybe we should work with @paraggit to add an IQE test that exercises the new internal API to verify in the ci.ext PR check that it always behaves as expected. Thoughts? Other than that, I think this is good to go.

2022-06-24 14:27 UTC, abellotti commented on cloudigrade/internal/views.py
> +            return Response(content_type="text/plain", data=value)
Thanks. I agree on tests. While the unit tests will exercise the LocMemCache, Parag's ci.ext will exercise the Redis side of things.

2022-06-24 15:53 UTC, infinitewarp approved these changes
👍

2022-06-24 16:26 UTC, merged