Add overrides for DVO
cloudigrade/cloudigrade pull request #1246
Opened 2022-06-23 19:03 UTC by abellotti

- Add override for DVO so that the minimum check of 3 replicas is not enforced for cloudigrade-beat
and cloudigrade-listener where they must run with just 1 replica.

For: https://github.com/cloudigrade/cloudigrade/issues/1232

2022-06-27 16:29 UTC, abellotti commented
We're kind'a blocked and waiting for https://issues.redhat.com/browse/RHCLOUD-20060 so Clowder supports this.

2022-08-02 20:18 UTC, infinitewarp requested changes
Adding a note in here so we don't forget…

We may need to put similar annotations on [stage-smoke.yaml](https://github.com/cloudigrade/cloudigrade/blob/master/deployment/stage-smoke.yaml) because DVO in stage is reporting failures for `deployment_validation_operator_no_liveness_probe` and `deployment_validation_operator_no_readiness_probe`. See "Validation Details" on [this dsahboard](https://grafana.app-sre.devshift.net/d/dashdotdb/dash-db?orgId=1&var-datasource=dashdotdb-rds&var-cluster=crcs02ue1&var-namespace=cloudigrade-stage) to confirm.

_Or_ we need to reach out to the QE org to get them make whatever changes are necessary so that we don't need to ignore those checks on the smoke jobs.

2022-08-03 10:59 UTC, abellotti commented
/retest

2022-08-03 15:26 UTC, infinitewarp approved these changes
Looks good to me! 🎉 Here's hoping it works as expected in stage and prod! 🤞🍀

2022-08-03 15:30 UTC, infinitewarp approved these changes

2022-08-03 15:44 UTC, merged